# Generated by Django 5.1.6 on 2025-02-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GoodHabit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("place", models.CharField(max_length=100, verbose_name="Место")),
                ("lide_time", models.DateTimeField(verbose_name="Дата и время выполнения привычки")),
                ("action", models.CharField(max_length=500, verbose_name="Действие")),
                ("sing_good_habit", models.BooleanField(default=True, verbose_name="Признак полезной привычки")),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("Ежедневно", "Ежедневно"),
                            ("Раз в два дня", "Раз в два дня"),
                            ("По четным дням", "По четным дням"),
                            ("По нечетным дням", "По нечетным дням"),
                            ("Раз в неделю", "Раз в неделю"),
                        ],
                        default="Ежедневно",
                        max_length=20,
                        verbose_name="Переодичность",
                    ),
                ),
                ("time_to_complete", models.TimeField(verbose_name="Время на выполнениe привычки")),
                ("sing_of_publicity", models.BooleanField(default=True, verbose_name="Признак публичности")),
            ],
            options={
                "verbose_name": "Хорошая привычка",
                "verbose_name_plural": "Хорошие привычки",
            },
        ),
        migrations.CreateModel(
            name="NiceHabit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("place", models.CharField(max_length=100, verbose_name="Место")),
                ("lide_time", models.DateTimeField(verbose_name="Дата и время выполнения привычки")),
                ("action", models.CharField(max_length=500, verbose_name="Действие")),
                ("sing_nice_habit", models.BooleanField(default=True, verbose_name="Признак приятной привычки")),
                ("time_to_complete", models.TimeField(verbose_name="Время на выполнениe привычки")),
                ("sing_of_publicity", models.BooleanField(default=True, verbose_name="Признак публичности")),
            ],
            options={
                "verbose_name": "Приятная привычка",
                "verbose_name_plural": "Приятные привычки",
            },
        ),
        migrations.CreateModel(
            name="RelatedHabit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reward", models.CharField(blank=True, max_length=250, null=True, verbose_name="Вознаграждение")),
            ],
            options={
                "verbose_name": "Связанная привычка",
                "verbose_name_plural": "Связанные привычки",
            },
        ),
    ]
