# Generated by Django 5.1.6 on 2025-02-13 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("habits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="goodhabit",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Пользователь"
            ),
        ),
        migrations.AddField(
            model_name="relatedhabit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="habits.nicehabit",
                verbose_name="Связанная привычка",
            ),
        ),
        migrations.AddField(
            model_name="goodhabit",
            name="related_habit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="habits.relatedhabit",
                verbose_name="Связанная привычка или вознаграждение",
            ),
        ),
    ]
