# Generated by Django 5.1.6 on 2025-02-13 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="relatedhabit",
            options={
                "verbose_name": "Связанная привычка или вознаграждение",
                "verbose_name_plural": "Связанные привычки или вознаграждения",
            },
        ),
    ]
