# Generated by Django 5.1.6 on 2025-02-13 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_relatedhabit_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goodhabit",
            name="sing_good_habit",
        ),
        migrations.RemoveField(
            model_name="nicehabit",
            name="sing_nice_habit",
        ),
    ]
